apiVersion: v1
data:
  volcano-scheduler.conf: |
    actions: "reclaim, allocate, preempt, backfill"
    tiers:
    - plugins:
      - name: priority
        enablePreemptable: true
      - name: gang
        enablePreemptable: false
      - name: conformance
      - name: sla
    - plugins:
      - name: overcommit
        arguments:
          overcommit-factor: 2.0
      - name: drf
        enablePreemptable: false
      - name: predicates
      - name: capacity # capacity plugin must be enabled
        enableHierarchy: true # enable hierarchical queue
      - name: nodeorder
      - name: binpack
        arguments:
          binpack.resources: nvidia.com/gpu
          binpack.resources.nvidia.com/gpu: 4
kind: ConfigMap
metadata:
  name: volcano-scheduler-configmap
  namespace: volcano-system
